babelcloud/gbox

packages/mcp-server/src/tools/run-python.ts

- Use run-bash tool for uv in run-python.ts

:pencil: docs: update Python package installation instructions

---

Makefile
manifests/docker/docker-compose.yml
packages/api-server/config/config.go
packages/api-server/config/config.yaml
packages/api-server/config/file_config.go
packages/api-server/handlers/docker/create.go

- Introduce Makefile targets for server startup
- Update Docker Compose for host share directory
- Enhance API config for environment variable binding
- Modify file config and box creation logic

:star: feat: add API and MCP server startup commands

---

packages/api-server/handlers/docker/run.go
packages/api-server/models/box_run.go
packages/mcp-server/src/tools/run-bash.ts
packages/mcp-server/src/tools/run-python.ts

- Refactor to include Box details
- Clarify package installation in documentation
- Improve comments on box management

:sparkles: feat: update BoxRunResponse structure

---

LICENSE
Makefile
README.md
packages/api-server/Makefile
packages/mcp-server/package.json

- Enhance Makefile with new Docker build commands
- Improve README for development instructions

chore: update license year and owner

---

packages/api-server/main.go

- Introduce POST endpoint '/boxes/reclaim' for inactive boxes
- Add response models for success and error handling
```
❯ ./gbox box reclaim
Box reclamation completed successfully
```
resolves: https://github.com/babelcloud/gru-sandbox/issues/32

:star: feat: add endpoint to reclaim inactive boxes

---

packages/cli/Makefile
packages/cli/bin/gbox
packages/cli/cmd/box.go
packages/cli/cmd/box_create.go
packages/cli/cmd/root.go
packages/cli/config/config.go

* Use Cobra's Built-in Help System
* Improved `packages/cli/bin/gbox` Script
* Optimize Command Execution Logic

perf: refact 'create' to follow Cobra best practices

---

.env
packages/cli/cmd/box_cp.go
packages/cli/cmd/box_cp_test.go
packages/cli/cmd/box_delete.go
packages/cli/cmd/box_exec.go
packages/cli/cmd/box_exec_test.go
packages/cli/cmd/box_inspect.go
packages/cli/cmd/box_inspect_test.go
packages/cli/cmd/box_list.go
packages/cli/cmd/box_list_test.go
packages/cli/cmd/box_reclaim.go
packages/cli/cmd/box_reclaim_test.go
packages/cli/cmd/box_start.go
packages/cli/cmd/box_start_test.go
packages/cli/cmd/box_stop.go
packages/cli/cmd/box_stop_test.go
packages/cli/e2e/box-exec.exp
packages/cli/e2e/run-test
packages/cli/go.mod
packages/cli/go.sum

1. Implemented `exec` function with go (Solved cobra `--` parameter parsing issue with cmd.Args LenAtDash()
2. Refact box cmd to follow Cobra best pratices of args parse

⬆️ refact box cmd to follow Cobra best practices

---

packages/cli/Makefile
packages/cli/cmd/mcp.go
packages/cli/cmd/mcp_export.go
packages/cli/cmd/mcp_export_test.go
packages/cli/config/config.go

migrate-mcp-cmd to go impl

---

images/Makefile
images/python/.dockerignore
images/python/Dockerfile
images/python/test.sh
images/python/test/.gitignore
images/python/test/Dockerfile
images/python/test/test_playwright.py

- Add test support in Makefile with test-% target
- Update help command for clearer display of targets/images
- Refactor Dockerfile to install dependencies in a single layer
- Set environment variables for Playwright and update CMD

:zap: improvement: enhance Dockerfile and Makefile for image management

---

packages/api-server/internal/browser/service/context.go
packages/api-server/internal/browser/service/page.go
packages/api-server/internal/browser/service/page_action.go
packages/api-server/internal/browser/service/page_action_snapshot.go
packages/api-server/internal/browser/service/page_action_vision.go
packages/api-server/internal/browser/service/service.go
packages/api-server/pkg/browser/page_action.go
packages/api-server/pkg/browser/page_action_params.go
packages/api-server/pkg/browser/page_action_result.go
packages/api-server/pkg/browser/page_action_types.go

- Change CreateContext to use CreateContextParams and CreateContextResult
- Enhance ExecuteAction for structured failure results
- Introduce getCurrentPages for open page state retrieval
- Update PageActionParams to use json.RawMessage
- Improve error messages and logging

:rotating_light: refactor: update context and page action handling

---

manifests/docker/docker-compose.yml
packages/cli/cmd/script/gbox-cluster-docker

before release a new version, i found
* mcp-server will keep crashing if applying docker compose, consider now we use stdio mode for mcp-server. We chose not to start mcp-server in sse mode
* fix a env bug in docker compose yaml

🐛 fix: tag name match error

---

Makefile

https://github.com/Homebrew/homebrew-core/pull/228217#discussion_r2173269687

standardize installing homebrew-dist

---

packages/mcp-android-server/src/mcp-server.ts
packages/mcp-android-server/src/tools/apk-management.ts
packages/mcp-android-server/src/tools/index.ts
packages/mcp-android-server/src/tools/type-text.ts
packages/mcp-android-server/src/tools/ui-action.ts

⬆️ android mcp: support type text && slightly adjust on apkinstall and ui-action

---

packages/mcp-android-server/src/tools/ui-action.ts

🐛fix: ui-action settings param

---

README.md
packages/cli/cmd/box_create.go
packages/cli/cmd/box_create_ad.go
packages/cli/cmd/box_create_ln.go

 ⬆️ upgrade: support android box create

---

packages/cli/cmd/box_exec.go
packages/mcp-android-server/package.json
packages/mcp-android-server/pnpm-lock.yaml
packages/mcp-android-server/src/mcp-server.ts
packages/mcp-android-server/src/tools/adb-shell.ts
packages/mcp-android-server/src/tools/index.ts
packages/mcp-android-server/src/tools/logcat.ts

⭐️ feat: mcp-server support logcat and adb shell cmd

---

.github/workflows/release.yml
Makefile
packages/cli-npm/cli.js
packages/cli-npm/install.js
packages/cli-npm/package.json
packages/cli-npm/pnpm-lock.yaml
packages/cli-npm/uninstall.js
packages/cli/.gitignore
packages/cli/Makefile
packages/cli/cmd/box_create.go
packages/cli/cmd/box_create_ad.go
packages/cli/cmd/box_exec.go
packages/cli/cmd/box_exec_unix.go
packages/cli/cmd/box_exec_windows.go

关于 npm 包名和其他信息还会调整，不是最终版本，这个 PR 的主要支持 github release windows 版本 gbox
合并后会测一下 windows 版本是否正常工作

👾 prepare: win-pkg and npm install @gbox/cli

---

packages/cli/cmd/device_connect.go
packages/cli/cmd/device_connect_list.go
packages/cli/internal/device_connect/client.go
packages/cli/internal/device_connect/daemon.go
packages/cli/internal/device_connect/daemon_unix.go
packages/cli/internal/device_connect/daemon_windows.go

- Changed references from Udid to Id for consistency.
- Updated DeviceInfo struct with Id field.
- Simplified environment variable setup in proxy service.
Enhances clarity and uniformity in device identification.

:recycle: refactor: update device identifier from Udid to Id

---

.github/workflows/release.yml
Makefile

MCP server 删了，但是打包和CI没适配https://github.com/babelcloud/gbox/actions/runs/16926223318/job/47962287383

🐛 fix: ci and makefile

---

.github/workflows/release.yml

chore: clean up release workflow by removing unused artifact entries

:bug: fix: resolve release failure issue

---

packages/mcp-android-server/package.json
packages/mcp-android-server/src/config.ts
packages/mcp-android-server/src/gboxsdk/android.service.ts

mcp-release: update v0.1.6

---

packages/cli-npm/package.json

synchronize the versions of cli-npm

fix: update cli-npm version to 0.1.7

---

packages/cli/cmd/device_connect.go
packages/cli/cmd/profile.go
packages/cli/internal/profile/mgr.go

- Update profile structure to include fields for organization name and slug, ensuring backward compatibility.
- Refactor device connection output to use color formatting for better visibility.
- Add functionality to retrieve and display devices URL for the current profile.
- Improve organization name retrieval in profile commands for consistency.
- Streamline error handling in API calls related to organization information.

:rotating_light: refactor: enhance profile management and device output

---

packages/cli/cmd/device_connect.go

fix: actively exit device-proxy

---

packages/cli/cmd/box_cp.go
packages/cli/cmd/box_exec.go
packages/cli/cmd/login.go
packages/cli/config/config.go
packages/cli/internal/adb_expose/utils.go
packages/cli/internal/client/client.go
packages/cli/internal/cloud/client.go
packages/cli/internal/device_connect/daemon.go
packages/cli/internal/device_connect/downloader.go
packages/cli/internal/profile/mgr.go

- Simplify API URL construction by removing redundant path segments.
- Update base URL handling to ensure consistency across various components.
- Introduce migration logic for profile base URLs to align with new API structure.
- Enhance profile manager to cleanly save configurations without unnecessary base URL fields.

:rotating_light: refactor: align GBOX_BASE_URL with SDK by adding api/v1

---

packages/cli/cmd/profile.go
packages/cli/internal/profile/mgr.go

fix: profile use preview
